---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: olm
  namespace: flux-system
spec:
  interval: 4h0m0s
  ref:
    branch: master
  url: https://github.com/operator-framework/operator-lifecycle-manager.git

