apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: olm
  namespace: default
spec:
  interval: 15m
  path: "./deploy/upstream/quickstart"
  prune: true
  sourceRef:
    kind: GitRepository
    name: olm
