apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBhUK3r8Rq/AsJOcGiA6R3nm1d3l/oa9QeDHSyI4+Oe/1TKo3mrHrUt6R7aoq6rW6n5qX3rjtQrQhKc/MCHJK03oMJjMeGatLBBtO4VecsMahkuw62e9zZsPaymngA1wDCciE0PDeO0pDCmoSg15R//uq2xlFRPNyoo6sUvy9OD3PcmndDoCzoHG+eA1Jl565pHAoTGtp++lfKqOMITnjRlyMRP6zyWBBg3ql5vImXRpZ3tzXGu+yHgt5Iv400vaiO9YAa3wA12S4mth1GBUuh9k7ao2kbudVVoPWWx7ozpnLzs+RsF1wZ0mWlm6QBgiYOAqJAWqz812jq0v5Ax5YAaJsE3U0oWPuaV+ETq9bQ4GE9Fu+0kZDJ7cTXFYoysf/C25H7Ka3YkOwnX4tl+9B10/kXOzJ1tN7i4qhjUuedbzaTeo9khuKzADt6Bu7vJ8ELd2SmFGwy7zJ9z0QDghUv9x+DpwGXkyw3w2HtFY9453cIWvPBZWghkFa/J/bn58Bkoc4GTbJFhgVIyQ2X468te5j4eMb8VNcsMPsSqfu1OBE08U76rxwq8pNCJ5PHuxgRYsI/lQD7tozWr4ulLLTv0faZxIZHSA7IvJLAhC0Lqnhqx+CCX9CgE7dHT14yjkctzUSd+YODw/12hGTGIt1u84MpRGiMLBGXqX4fxv5NbzjyYFqloL+XdGJZcWNvvCLHAd6vjixJo5X81nUyd9+kMluLe1zmsZwunj1UDGDXfq6NMY48aUHsjmpOrbaboxxgvxYxDYximWY9DBg05uJ6ZNto3Mx/yY7+YX5LN9sCGwWDN+AdM68k8/hZ41bFasBH50cQQkdLhr9FHaqzkwIqNkqYJbVY5OPQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: discord-url
      namespace: flux-system

