apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: godaddy
  namespace: default
spec:
  encryptedData:
    api-key: AgB9fTYGEtAKoiy/3GdkARKEq9KrHTa9R9I7D3VWSHb/kkE0L9urSCdTvDAMHJ1dQYj+TnWQ4I/3ln9i4ZCT1Rmsq0PamJhdBPCMad2StBaY1o52PsfdxN1n7qY5zB7SjsD2wOShcnZpOWXUxQ2p591pPrXIkpgX73b4fKPMs0Eja/HqUjuls3qwuz6dh7aTyPSCIhtt4garvQdOpKeQh1M5f0JtqnVNKK+CRzSLl+HWVdYonoIvmEx2I/p8NRctX3DLnMAnu5VvScVeyF1MaRPzTrQl5Sa80o2uvEO1g8zO9aEM2fNCnYnd7texJILCegyWDFz5JiLBFn0VT4hCxr9YeYqMmaGl6w2Uu9QUQhQadGgj/HZrolezK5u/rGGPaIO98HUT7Bah8wkJyaNG54dNdulEhbiRxX8puHnNqgW2Oh7BPJaqiMpMSSm4s1dlPkkxwBvuL/fIaV1uuuFGEzmP7a8l2Ml2LpkLlAmKucdCz63D0UUpZttVw5ukfdqAe9YaJHI9NPIXtVDAjyCICJ4jc2NgLBonBreNCcWDGXP1uA4ic3eOmOllu67svftFjp2dRmCwn66tm4N+GMEQsL9tON5PwX8xjfdwSz6/8ZfXylK+vHOnrBIm/HGM4TbSRPVJaTM4IxKaDFN5S7qKEQ9sobiKazJOhdCgTEi/jy6p7GGpEXpuYM2MmLPvAu95+AxcLXNKwxQkTBkwmmIhfEjgDTs+3Ou8QJx5hMdG/ov2igJX3g==
    api-secret: AgB4rnuPKuCfdhlGfPmtD+ZeXoUrP11jbpkWrv+L6dz3CjkrbY3b0oQ0563aQqEwebhWWy8Vqj+BCAJ/Gdvi8rlCWdb5VXvXvfN63l0KBoeWVEY2WuPaab+GWphswDNytDg3+HAMkXFfeesD6vDAtUJznXojv3ci2irMFKmf+fOWT2b5sOwxrGs67RMEUhbENEimJl3QKcIvouCQntM+D4uymz7f/NpZUl0F6o6W6kX2JxVoJqzEC9MnX+81hgU1zxZpWVTrjorCVsRPG0URUIE84cEsYsXUHGE50iIHt6kM9o70aHRvORHvuHkKg+8CYnoWINQfR7eswg9xZQ1VgY3rUvrnbglO3uLIK9vi2q6KXYOP38TaNnknMUexgSORKUdLOw9wJtLk15lCH3rudENcahJ/812T3qNuYMauo+pxzABia6JJXowPJLfO/lw+nIEyx3S9eRM0iMa4+xoxhLnOtyIUW6qIbHkLlul2uL47yGx6mgh1L4KD1m8S+ldmQN1EXCR29bojCgi0utMCuBrFUkcrzci7pyQ/MUISWt0vBBTiCeLp8Xvwuirvfx0gBJ4dJWy+PsyFNaorBOuwRawvZtV+s43Ef1RjvEAA2OjgLkSf383gYUyzzDjra8IzNWCtibSuIgvuyK8Sjf+BF4M4qXykxWZ4RCbvAPr6CP4AEBYxmBZD8xQgxcu7mk7JTzIwME9hI6waECJqMRv/f47UAfGSDrHD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: godaddy
      namespace: default

